# Generated by Django 5.0.6 on 2024-05-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
