# Generated by Django 5.0.6 on 2024-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_commentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='post',
        ),
        migrations.AddField(
            model_name='commentpost',
            name='post_id',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
